##############################################################
# Sample: Vagrant for IOS XE Network Programmability Development
# Author: Hank Preston <hapresto@cisco.com>
#
# ansible_provision.yaml
# Illustrate the following concepts:
# - Provision an IOS XE Device through Ansible
# - Enable NETCONF/RESTCONF APIs and use them
# - Enable Guest Shell
##############################################################
---
- name: Provision IOS XE Devices
  hosts: all
  connection: local
  gather_facts: false
  vars_files: 
    - secrets.yaml

  tasks:
    - name: Enable IOX
      retries: 2
      delay: 5
      ios_config:
        provider: "{{ provider }}"
        lines:
         - iox

 #   - name: Pause for IOX to start
 #     pause:
 #       seconds: 45

    - name: Configure GigabitEthernet1
      ios_config:
        provider: "{{ provider }}"
        lines:
          - description Configured by Ansible with Vagrant
          - ip address dhcp
          - ip nat outside
        parents: interface GigabitEthernet1

    - name: Enable GigabitEthernet1
      ios_interface:
        provider: "{{ provider }}"
        name: GigabitEthernet1
        enabled: True

    - name: Configure GigabitEthernet2
      ios_config:
        provider: "{{ provider }}"
        lines:
          - description Configured by Ansible with Vagrant
          - ip address 192.168.100.20 255.255.255.0
        parents: interface GigabitEthernet2

    - name: Enable GigabitEthernet2
      ios_interface:
        provider: "{{ provider }}"
        name: GigabitEthernet2
        enabled: True

    - name: Configure VirtualPortGroup0
      ios_config:
        provider: "{{ provider }}"
        lines:
          - ip address 192.168.35.1 255.255.255.0
          - ip nat inside
        parents: interface VirtualPortGroup0

    - name: Configure NAT Access-list
      ios_config:
        provider: "{{ provider }}"
        lines:
          - permit 192.168.0.0 0.0.255.255
        parents: ip access-list standard NAT_ACL
        before: no ip access-list standard NAT_ACL
        match: exact

    - name: Configure NAT Rules
      ios_config:
        provider: "{{ provider }}"
        lines:
          - ip nat inside source list NAT_ACL interface GigabitEthernet1 overload
          - ip nat inside source static tcp 192.168.35.2 5000 interface GigabitEthernet1 5000

    - name: Enable Guest Shell
      ignore_errors: true
      ios_command:
        provider: "{{ provider }}"
        commands:
          - guestshell enable VirtualPortGroup 0 guest-ip 192.168.35.2 name-server 208.67.222.222
        wait_for:
          - result[0] contains wait
          - result[0] contains successfully

    - name: Install Git
      ignore_errors: true
      ios_command:
        provider: "{{ provider }}"
        commands:
          - guestshell run sudo yum install git -y
