##############################################################
# Sample: Vagrant for IOS XE Network Programmability Development
# Author: Hank Preston <hapresto@cisco.com>
#
# ansible_provision.yaml
# Illustrate the following concepts:
# - Provision an IOS XE Device through Ansible
# - Enable NETCONF/RESTCONF APIs and use them
# - Enable Guest Shell
##############################################################
---
- name: Provision IOS XE Devices
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Configure NETCONF and RESTCONF
      ios_config:
        provider:
          host: "{{mgmt_ip}}"
          port: "{{ssh_port}}"
          username: "{{username}}"
          password: "{{password}}"
        lines:
          - netconf-yang
          - netconf-yang cisco-odm polling-enable
          - restconf
          - ip http server
          - ip http secure-server

    - name: Enable IOX
      ios_config:
        provider:
          host: "{{mgmt_ip}}"
          port: "{{ssh_port}}"
          username: "{{username}}"
          password: "{{password}}"
        lines:
          - iox

    - name: Pause for NETCONF and IOX to start
      pause:
        seconds: 45

#    Ansible 2.4 version of the NETCONF module supports reading in NETCONF Files
    - name: "Generate NETCONF config"
      with_items: "{{interfaces}}"
      template:
        src: "netconf_interface_template.j2"
        dest: "./{{inventory_hostname}}-{{item.interface_type}}{{item.interface_id}}.xml"

    - name: Configure Interfaces
      with_items: "{{interfaces}}"
      netconf_config:
        host: "{{mgmt_ip}}"
        port: "{{netconf_port}}"
        hostkey_verify: false
        username: "{{username}}"
        password: "{{password}}"
        src: "./{{inventory_hostname}}-{{item.interface_type}}{{item.interface_id}}.xml"

    - name: Configure Interfaces and NAT for Guest Shell
      netconf_config:
        host: "{{mgmt_ip}}"
        port: "{{netconf_port}}"
        hostkey_verify: false
        username: "{{username}}"
        password: "{{password}}"
        src: "guestshell_prep_template.xml"
      tags: guestshell

    - name: Configure NAT for Guestshell Flask App
      ios_config:
        provider:
          host: "{{mgmt_ip}}"
          port: "{{ssh_port}}"
          username: "{{username}}"
          password: "{{password}}"
        lines:
          - ip nat inside source static tcp 192.168.35.2 5000 interface GigabitEthernet1 5000

    - name: Enable Guest Shell
      ignore_errors: true
      ios_command:
        provider:
          host: "{{mgmt_ip}}"
          port: "{{ssh_port}}"
          username: "{{username}}"
          password: "{{password}}"
          timeout: 60
        commands:
          - guestshell enable VirtualPortGroup 0 guest-ip 192.168.35.2 name-server 208.67.222.222
      tags: guestshell

    - name: Install Git
      ignore_errors: true
      ios_command:
        provider:
          host: "{{mgmt_ip}}"
          port: "{{ssh_port}}"
          username: "{{username}}"
          password: "{{password}}"
          timeout: 180
        commands:
          - guestshell run sudo yum install git -y
      tags: guestshell    
